name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: "ftp.mrpgmanagement.com"
        ftp-username: "workflow@mrpgmanagement.com"
        ftp-password: "S(OO3UHZMJs="
        local-dir: ./
        git-ftp-args: --insecure # Optional: Additional arguments for git-ftp
